### ISSUE TITLE
Check Delete Property

### ISSUE THREAD

**Issue by zachintosh** [byuitechops/action-series-assignments#4]
https://github.com/byuitechops/action-series-assignments/blob/44dad761fbd5a801a2130afdac05166410f28d97/actions/assignments-delete.js#L3-L5

For readability, lets make this `item.techops.delete === true` instead of just checking if it is truthy. That also prevents any issues where the value for `item.techops.delete` is set to something else that might be truthy. Doubt it would ever happen, but ya know.

**Comment by sethchilders92** [comment]
Resolved
